[package]
name = "rustify-telegram"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
serde = "1.0.228"
serde_json = "1.0.147"
env_logger = "0.11.8"
reqwest = { version = "0.12.28", features = ["json"] }
log = "0.4.29"
strum = "0.27.2"
strum_macros = "0.27.2"